export const USERS_FETCH_START = "USERS_FETCH_START";
export const USERS_FETCH_END = "USERS_FETCH_END";
export const USERS_FETCH_ERROR = "USERS_FETCH_ERROR";
export const USERS_SEARCH_BOX = "USERS_SEARCH_BOX";